MCU=atmega32
AVRDUDEMCU=m32
TARGET=blinky
HFUSE=0x99

# 10000 - very slow but works
# 220000 - roughtly as fast as 1Mhz ATmega32a can go.
BAUD=220000

#F_CPU=1000000UL
#LFUSE=0xE1

F_CPU=8000000UL
LFUSE=0xE4

#F_CPU=16000000UL
#LFUSE=0xCF

include Makefile.all
